
spring:
  application:
    name: config-client
  cloud:
    config:
      label: master
      profile: dev
      uri: http://localhost:8888/
server:
    port: 8766
#eureka:
#    client:
#        serviceUrl:
#            defaultZone: http://localhost:8761/eureka/
#spring:
#    application:
#        name: eureka-helloworld