spring:
  application:
    name: server

server:
  port: 8761
eureka:
  instance:
    hostname: localhost
    logging:
      level:
        com.netflix.discovery: 'OFF'
        org.springframework.cloud: 'DEBUG'

    elicent:
      registerWithEureka : false
      fetchRegistry : false
      serviceUrl:
        defaultZone : http://${eureka.instance.hostname}:${server.port}/eureka/
